// apps/vue/src/components/DatePicker/DatePicker.vue
<script setup lang="ts">
/**
 * Public DatePicker component.
 *
 * Owns a `useDatePicker` engine instance and wires it to a text input +
 * teleported popover. The component itself only handles UI plumbing —
 * positioning, open/close, click-outside dismissal, and the v-model
 * contract. All calendar math lives in the engine.
 */
import { computed, nextTick, onBeforeUnmount, ref, useId, watch } from 'vue'

import type { PlainDateLike, Weekday } from '@datepicker/core'

import { useDatePicker } from '../../composables/useDatePicker'
import DatePickerPopover from './DatePickerPopover.vue'
import '@datepicker/styles/datepicker.css'

interface Props {
  /** ISO `YYYY-MM-DD` string, or `null` when no date is selected. */
  modelValue?: string | null
  min?: string | null
  max?: string | null
  locale?: string
  weekStartsOn?: Weekday
  placeholder?: string
  disabled?: boolean
  name?: string
  id?: string
  /** Optional override for the input's display formatter. */
  formatInput?: (date: PlainDateLike | null) => string
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: null,
  min: null,
  max: null,
  locale: 'en-US',
  placeholder: 'Select a date',
  disabled: false,
})

const emit = defineEmits<{
  (event: 'update:modelValue', value: string | null): void
  (event: 'open'): void
  (event: 'close'): void
}>()

const { state, grid, actions, formatDayLabel, parseISO } = useDatePicker({
  initialDate: props.modelValue,
  min: props.min,
  max: props.max,
  locale: props.locale,
  ...(props.weekStartsOn !== undefined ? { weekStartsOn: props.weekStartsOn } : {}),
})

const fallbackId = useId()
const inputId = computed(() => props.id ?? fallbackId)

const isOpen = ref(false)
const inputRef = ref<HTMLInputElement | null>(null)
const popoverRef = ref<HTMLElement | null>(null)
const popoverPosition = ref({ top: 0, left: 0, minWidth: 0 })

const inputDisplay = computed(() => {
  const date = state.value.selected
  if (props.formatInput) return props.formatInput(date)
  return date ? formatDateForInput(date) : ''
})

function formatDateForInput(date: PlainDateLike): string {
  return new Intl.DateTimeFormat(state.value.locale, { dateStyle: 'medium' }).format(
    date.toNativeDate(),
  )
}

/* ------------------------------------------------------------------ */
/* Sync external props into the engine                                */
/* ------------------------------------------------------------------ */

watch(
  () => props.modelValue,
  (next) => {
    const current = state.value.selected?.toISO() ?? null
    if (next === current) return
    if (next === null) {
      actions.clear()
    } else {
      actions.select(next)
    }
  },
)

watch(() => props.locale, (next) => actions.setLocale(next))
watch(() => props.min, (next) => actions.setMin(next))
watch(() => props.max, (next) => actions.setMax(next))

/* ------------------------------------------------------------------ */
/* Open / close                                                       */
/* ------------------------------------------------------------------ */

function open() {
  if (isOpen.value || props.disabled) return
  isOpen.value = true
  emit('open')
  nextTick(updatePosition)
  // Defer outside-click registration so the same click doesn't close it.
  setTimeout(() => {
    document.addEventListener('pointerdown', handlePointerDown, true)
    window.addEventListener('resize', updatePosition)
    window.addEventListener('scroll', updatePosition, true)
  }, 0)
}

function close({ restoreFocus = true } = {}) {
  if (!isOpen.value) return
  isOpen.value = false
  document.removeEventListener('pointerdown', handlePointerDown, true)
  window.removeEventListener('resize', updatePosition)
  window.removeEventListener('scroll', updatePosition, true)
  emit('close')
  if (restoreFocus) inputRef.value?.focus()
}

function handlePointerDown(event: PointerEvent) {
  const target = event.target as Node | null
  if (!target) return
  if (inputRef.value?.contains(target)) return
  if (popoverRef.value?.contains(target)) return
  close({ restoreFocus: false })
}

function updatePosition() {
  const rect = inputRef.value?.getBoundingClientRect()
  if (!rect) return
  popoverPosition.value = {
    top: rect.bottom + window.scrollY + 4,
    left: rect.left + window.scrollX,
    minWidth: rect.width,
  }
}

onBeforeUnmount(() => {
  document.removeEventListener('pointerdown', handlePointerDown, true)
  window.removeEventListener('resize', updatePosition)
  window.removeEventListener('scroll', updatePosition, true)
})

/* ------------------------------------------------------------------ */
/* Engine actions                                                     */
/* ------------------------------------------------------------------ */

function handleSelect(date: PlainDateLike) {
  actions.select(date)
  emit('update:modelValue', date.toISO())
  close()
}

function handleToday() {
  actions.goToToday()
}

function handleClear() {
  actions.clear()
  emit('update:modelValue', null)
}

function handleInputChange(event: Event) {
  const target = event.target as HTMLInputElement
  const parsed = parseISO(target.value)
  if (parsed) {
    actions.select(parsed)
    emit('update:modelValue', parsed.toISO())
  } else if (target.value === '') {
    actions.clear()
    emit('update:modelValue', null)
  }
}

/* ------------------------------------------------------------------ */
/* Keyboard handling                                                  */
/* ------------------------------------------------------------------ */

function focusActiveDayCell() {
  const popover = popoverRef.value
  if (!popover) return
  const target = popover.querySelector<HTMLElement>('[data-focused="true"]')
  target?.focus()
}

watch(
  () => state.value.focused.toISO(),
  () => {
    if (!isOpen.value) return
    nextTick(focusActiveDayCell)
  },
)

watch(isOpen, (open) => {
  if (!open) return
  nextTick(focusActiveDayCell)
})

function handleInputKeydown(event: KeyboardEvent) {
  switch (event.key) {
    case 'ArrowDown':
    case 'Enter':
    case ' ':
      if (!isOpen.value) {
        event.preventDefault()
        open()
      }
      break
    case 'Escape':
      if (isOpen.value) {
        event.preventDefault()
        close()
      }
      break
  }
}

function handlePopoverKeydown(event: KeyboardEvent) {
  if (!isOpen.value) return

  switch (event.key) {
    case 'Escape':
      event.preventDefault()
      close()
      return
    case 'Enter':
    case ' ': {
      // Only handle when a day cell is focused — otherwise let buttons fire.
      const isOnDay = (event.target as HTMLElement | null)?.classList.contains('dp-day')
      if (!isOnDay) return
      event.preventDefault()
      const focusedCell = grid.value.find((cell) => cell.isFocused)
      if (focusedCell && !focusedCell.isDisabled) handleSelect(focusedCell.date)
      return
    }
    case 'ArrowLeft':
      event.preventDefault()
      actions.moveFocusByDays(-1)
      return
    case 'ArrowRight':
      event.preventDefault()
      actions.moveFocusByDays(1)
      return
    case 'ArrowUp':
      event.preventDefault()
      actions.moveFocusByDays(-7)
      return
    case 'ArrowDown':
      event.preventDefault()
      actions.moveFocusByDays(7)
      return
    case 'Home':
      event.preventDefault()
      actions.moveFocusToStartOfWeek()
      return
    case 'End':
      event.preventDefault()
      actions.moveFocusToEndOfWeek()
      return
    case 'PageUp':
      event.preventDefault()
      if (event.shiftKey) actions.moveFocusByYears(-1)
      else actions.moveFocusByMonths(-1)
      return
    case 'PageDown':
      event.preventDefault()
      if (event.shiftKey) actions.moveFocusByYears(1)
      else actions.moveFocusByMonths(1)
      return
    case 'Tab':
      // Tab leaves the popover entirely; close so focus flow is predictable.
      close({ restoreFocus: false })
      return
  }
}
</script>

<template>
  <div class="dp-root">
    <input
      :id="inputId"
      ref="inputRef"
      type="text"
      class="dp-input"
      :name="name"
      :placeholder="placeholder"
      :disabled="disabled"
      :value="inputDisplay"
      autocomplete="off"
      :aria-haspopup="'dialog'"
      :aria-expanded="isOpen"
      :aria-controls="`${inputId}-popover`"
      @focus="open"
      @click="open"
      @change="handleInputChange"
      @keydown="handleInputKeydown"
    />

    <Teleport to="body">
      <div
        v-if="isOpen"
        :id="`${inputId}-popover`"
        ref="popoverRef"
        class="dp-root"
        :style="{
          position: 'absolute',
          top: `${popoverPosition.top}px`,
          left: `${popoverPosition.left}px`,
          minWidth: `${popoverPosition.minWidth}px`,
        }"
        @keydown="handlePopoverKeydown"
      >
        <DatePickerPopover
          :state="state"
          :cells="grid"
          :format-day-label="formatDayLabel"
          @select="handleSelect"
          @prev-month="actions.goToPrevMonth"
          @next-month="actions.goToNextMonth"
          @today="handleToday"
          @clear="handleClear"
        />
      </div>
    </Teleport>
  </div>
</template>

// apps/react/src/components/DatePicker.tsx
/**
 * Public DatePicker component (React).
 *
 * Holds a `useDatePicker` engine instance and wires it to a text input +
 * portal popover. UI plumbing only — positioning, open/close, click-outside
 * dismissal, controlled `value` / `onChange`. All calendar math lives in
 * the engine.
 */

import {
  useCallback,
  useEffect,
  useId,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type ChangeEvent,
  type KeyboardEvent,
} from 'react'
import { createPortal } from 'react-dom'

import type { PlainDateLike, Weekday } from '@datepicker/core'

import { useDatePicker } from '../hooks/useDatePicker'
import { DatePickerPopover } from './DatePickerPopover'
import '@datepicker/styles/datepicker.css'

export interface DatePickerProps {
  /** ISO `YYYY-MM-DD` string, or `null` when no date is selected. */
  value?: string | null
  onChange?: (value: string | null) => void
  min?: string | null
  max?: string | null
  locale?: string
  weekStartsOn?: Weekday
  placeholder?: string
  disabled?: boolean
  name?: string
  id?: string
  /** Optional override for the input's display formatter. */
  formatInput?: (date: PlainDateLike | null) => string
  onOpen?: () => void
  onClose?: () => void
}

interface PopoverPosition {
  top: number
  left: number
  minWidth: number
}

const INITIAL_POSITION: PopoverPosition = { top: 0, left: 0, minWidth: 0 }

export function DatePicker({
  value = null,
  onChange,
  min = null,
  max = null,
  locale = 'en-US',
  weekStartsOn,
  placeholder = 'Select a date',
  disabled = false,
  name,
  id,
  formatInput,
  onOpen,
  onClose,
}: DatePickerProps) {
  const fallbackId = useId()
  const inputId = id ?? fallbackId
  const popoverId = `${inputId}-popover`

  const initialOptions = useMemo(
    () => ({
      initialDate: value,
      min,
      max,
      locale,
      ...(weekStartsOn !== undefined ? { weekStartsOn } : {}),
    }),
    // The engine is constructed once; props are synced through dedicated
    // setters below. Disable the lint rule here because the dependency
    // closure intentionally captures only the initial values.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  )

  const { state, grid, actions, formatDayLabel, parseISO } = useDatePicker(initialOptions)

  const [isOpen, setIsOpen] = useState(false)
  const [position, setPosition] = useState<PopoverPosition>(INITIAL_POSITION)
  const inputRef = useRef<HTMLInputElement | null>(null)
  const popoverRef = useRef<HTMLDivElement | null>(null)

  /* -------------------------------------------------------------- */
  /* External prop sync (engine setters)                            */
  /* -------------------------------------------------------------- */

  useEffect(() => {
    const current = state.selected?.toISO() ?? null
    if (value === current) return
    if (value === null) actions.clear()
    else actions.select(value)
    // `state.selected` is intentionally excluded; we only react to outer
    // value changes to push them down into the engine.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value])

  useEffect(() => {
    actions.setLocale(locale)
  }, [actions, locale])

  useEffect(() => {
    actions.setMin(min)
  }, [actions, min])

  useEffect(() => {
    actions.setMax(max)
  }, [actions, max])

  /* -------------------------------------------------------------- */
  /* Display value                                                  */
  /* -------------------------------------------------------------- */

  const inputValue = useMemo(() => {
    const date = state.selected
    if (formatInput) return formatInput(date)
    if (!date) return ''
    return new Intl.DateTimeFormat(state.locale, { dateStyle: 'medium' }).format(
      date.toNativeDate(),
    )
  }, [formatInput, state.selected, state.locale])

  /* -------------------------------------------------------------- */
  /* Positioning                                                    */
  /* -------------------------------------------------------------- */

  const updatePosition = useCallback(() => {
    const rect = inputRef.current?.getBoundingClientRect()
    if (!rect) return
    setPosition({
      top: rect.bottom + window.scrollY + 4,
      left: rect.left + window.scrollX,
      minWidth: rect.width,
    })
  }, [])

  useLayoutEffect(() => {
    if (!isOpen) return
    updatePosition()
    window.addEventListener('resize', updatePosition)
    window.addEventListener('scroll', updatePosition, true)
    return () => {
      window.removeEventListener('resize', updatePosition)
      window.removeEventListener('scroll', updatePosition, true)
    }
  }, [isOpen, updatePosition])

  /* -------------------------------------------------------------- */
  /* Open / close                                                   */
  /* -------------------------------------------------------------- */

  const open = useCallback(() => {
    if (disabled) return
    setIsOpen((wasOpen) => {
      if (wasOpen) return wasOpen
      onOpen?.()
      return true
    })
  }, [disabled, onOpen])

  const close = useCallback(
    ({ restoreFocus = true }: { restoreFocus?: boolean } = {}) => {
      setIsOpen((wasOpen) => {
        if (!wasOpen) return wasOpen
        onClose?.()
        if (restoreFocus) {
          // Defer to allow the popover to unmount before focusing back.
          queueMicrotask(() => inputRef.current?.focus())
        }
        return false
      })
    },
    [onClose],
  )

  useEffect(() => {
    if (!isOpen) return
    const handlePointerDown = (event: PointerEvent) => {
      const target = event.target as Node | null
      if (!target) return
      if (inputRef.current?.contains(target)) return
      if (popoverRef.current?.contains(target)) return
      close({ restoreFocus: false })
    }
    document.addEventListener('pointerdown', handlePointerDown, true)
    return () => {
      document.removeEventListener('pointerdown', handlePointerDown, true)
    }
  }, [isOpen, close])

  /* -------------------------------------------------------------- */
  /* Engine actions                                                 */
  /* -------------------------------------------------------------- */

  const handleSelect = useCallback(
    (date: PlainDateLike) => {
      actions.select(date)
      onChange?.(date.toISO())
      close()
    },
    [actions, close, onChange],
  )

  const handleToday = useCallback(() => {
    actions.goToToday()
  }, [actions])

  const handleClear = useCallback(() => {
    actions.clear()
    onChange?.(null)
  }, [actions, onChange])

  const handleInputChange = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => {
      const next = event.target.value
      if (next === '') {
        actions.clear()
        onChange?.(null)
        return
      }
      const parsed = parseISO(next)
      if (parsed) {
        actions.select(parsed)
        onChange?.(parsed.toISO())
      }
    },
    [actions, onChange, parseISO],
  )

  /* -------------------------------------------------------------- */
  /* Keyboard handling                                              */
  /* -------------------------------------------------------------- */

  // Move DOM focus to the day cell whose state.focused matches, so arrow
  // keys keep working as the user navigates between dates.
  useEffect(() => {
    if (!isOpen) return
    queueMicrotask(() => {
      const target = popoverRef.current?.querySelector<HTMLElement>(
        '[data-focused="true"]',
      )
      target?.focus()
    })
  }, [isOpen, state.focused])

  const handleInputKeyDown = useCallback(
    (event: KeyboardEvent<HTMLInputElement>) => {
      switch (event.key) {
        case 'ArrowDown':
        case 'Enter':
        case ' ':
          if (!isOpen) {
            event.preventDefault()
            open()
          }
          break
        case 'Escape':
          if (isOpen) {
            event.preventDefault()
            close()
          }
          break
      }
    },
    [close, isOpen, open],
  )

  const handlePopoverKeyDown = useCallback(
    (event: KeyboardEvent<HTMLDivElement>) => {
      if (!isOpen) return

      switch (event.key) {
        case 'Escape':
          event.preventDefault()
          close()
          return
        case 'Enter':
        case ' ': {
          const target = event.target as HTMLElement | null
          if (!target?.classList.contains('dp-day')) return
          event.preventDefault()
          const focusedCell = grid.find((cell) => cell.isFocused)
          if (focusedCell && !focusedCell.isDisabled) handleSelect(focusedCell.date)
          return
        }
        case 'ArrowLeft':
          event.preventDefault()
          actions.moveFocusByDays(-1)
          return
        case 'ArrowRight':
          event.preventDefault()
          actions.moveFocusByDays(1)
          return
        case 'ArrowUp':
          event.preventDefault()
          actions.moveFocusByDays(-7)
          return
        case 'ArrowDown':
          event.preventDefault()
          actions.moveFocusByDays(7)
          return
        case 'Home':
          event.preventDefault()
          actions.moveFocusToStartOfWeek()
          return
        case 'End':
          event.preventDefault()
          actions.moveFocusToEndOfWeek()
          return
        case 'PageUp':
          event.preventDefault()
          if (event.shiftKey) actions.moveFocusByYears(-1)
          else actions.moveFocusByMonths(-1)
          return
        case 'PageDown':
          event.preventDefault()
          if (event.shiftKey) actions.moveFocusByYears(1)
          else actions.moveFocusByMonths(1)
          return
        case 'Tab':
          // Tab leaves the popover entirely; close so focus flow stays predictable.
          close({ restoreFocus: false })
          return
      }
    },
    [actions, close, grid, handleSelect, isOpen],
  )

  return (
    <div className="dp-root">
      <input
        id={inputId}
        ref={inputRef}
        type="text"
        className="dp-input"
        name={name}
        placeholder={placeholder}
        disabled={disabled}
        value={inputValue}
        autoComplete="off"
        aria-haspopup="dialog"
        aria-expanded={isOpen}
        aria-controls={popoverId}
        onFocus={open}
        onClick={open}
        onChange={handleInputChange}
        onKeyDown={handleInputKeyDown}
      />

      {isOpen &&
        createPortal(
          <div
            id={popoverId}
            ref={popoverRef}
            className="dp-root"
            style={{
              position: 'absolute',
              top: position.top,
              left: position.left,
              minWidth: position.minWidth,
            }}
            onKeyDown={handlePopoverKeyDown}
          >
            <DatePickerPopover
              state={state}
              cells={grid}
              formatDayLabel={formatDayLabel}
              onSelect={handleSelect}
              onPrevMonth={actions.goToPrevMonth}
              onNextMonth={actions.goToNextMonth}
              onToday={handleToday}
              onClear={handleClear}
            />
          </div>,
          document.body,
        )}
    </div>
  )
}
